const students = [
  { name: "Alex Zelinsky", imageUrl: "https://avatars.githubusercontent.com/u/95510710?v=4" },
  { name: "Allan Yang", imageUrl: "http://www.ayang740.com/assets/img/profile.jpg" },
  { name: "Benjamin (Ben) Durham", imageUrl: "https://avatars.githubusercontent.com/u/103156527?v=4" },
  { name: "Brendan Lau", imageUrl: "https://avatars.githubusercontent.com/u/101230473?v=4" },
  { name: "Brian Aguilar", imageUrl: "https://avatars.githubusercontent.com/u/100168977?v=4" },
  { name: "Calvin Lieu", imageUrl: "https://avatars.githubusercontent.com/u/98150408?v=4" },
  { name: "David Jetsupphasuk", imageUrl: "https://avatars.githubusercontent.com/u/102331121?v=4" },
  { name: "Erik Nguyen", imageUrl: "https://avatars.githubusercontent.com/u/46208016?v=4" },
  { name: "Fangru Zhou", imageUrl: "https://avatars.githubusercontent.com/u/101694480?v=4" },
  { name: "Grant Christopherson", imageUrl: "https://avatars.githubusercontent.com/u/95774634?v=4" },
  { name: "Hansen Guo", imageUrl: "https://avatars.githubusercontent.com/u/77709211?v=4" },
  { name: "Heng Wang", imageUrl: "https://avatars.githubusercontent.com/u/8013146?v=4" },
  { name: "Hui (Abby) Feng", imageUrl: "https://media-exp1.licdn.com/dms/image/C5603AQGoKGzw1A4b3w/profile-displayphoto-shrink_400_400/0/1663562377067?e=1669248000&v=beta&t=7_ezFAvsHnX8XMfyUk3MsRG3b-AvkL0cXZAS3Jt-xBs" },
  { name: "Irving Arreola Palacios", imageUrl: "https://avatars.githubusercontent.com/u/96028000?v=4" },
  { name: "Isabel Arredondo", imageUrl: "https://avatars.githubusercontent.com/u/98997692?v=4" },
  { name: "Jair Carbajal", imageUrl: "https://avatars.githubusercontent.com/u/28913072?v=4" },
  { name: "Joel Cruz", imageUrl: "https://avatars.githubusercontent.com/u/79065322?v=4" },
  { name: "Jonatan Aguilar", imageUrl: "https://avatars.githubusercontent.com/u/61948122?v=4" },
  { name: "Kevin Gao", imageUrl: "https://avatars.githubusercontent.com/u/100536560?v=4" },
  { name: "Kevin Zhang", imageUrl: "https://avatars.githubusercontent.com/u/44452044?v=4" },
  { name: "Krista Strucke", imageUrl: "https://krista.red/images/new_linkedin.jpg" },
  { name: "Lynn Luong", imageUrl: "https://avatars.githubusercontent.com/u/100899731?v=4" },
  { name: "Lynnette Nguyen", imageUrl: "https://avatars.githubusercontent.com/u/98368183?v=4" },
  { name: "Qiaoyi (Joyce) Liu", imageUrl: "https://avatars.githubusercontent.com/u/92266749?v=4" },
  { name: "Qing (Alice) Li", imageUrl: "https://avatars.githubusercontent.com/u/93701088?v=4" },
  { name: "Rongrong (Renee) Luo", imageUrl: "https://avatars.githubusercontent.com/u/103155560?v=4" },
  { name: "Samantha (Sam) Weglinski", imageUrl: "https://avatars.githubusercontent.com/u/32751992?v=4" },
  { name: "Sang Joon (Joon) Bae", imageUrl: "https://avatars.githubusercontent.com/u/94085979?v=4" },
  { name: "Thomas (Drew) Anton", imageUrl: "https://avatars.githubusercontent.com/u/101833447?v=4" },
  { name: "Timothy (Tim) Reinhardt", imageUrl: "https://avatars.githubusercontent.com/u/95321368?v=4" },
  { name: "Ting Feng", imageUrl: "https://avatars.githubusercontent.com/u/101086307?v=4" },
  { name: "Varsha Harikishan Gade", imageUrl: "https://avatars.githubusercontent.com/u/88607196?v=4" },
  { name: "Wanting (Christine) Zhang", imageUrl: "https://avatars.githubusercontent.com/u/99835281?v=4" },
  { name: "Waseem Alame", imageUrl: "https://avatars.githubusercontent.com/u/73668892?v=4" },
  { name: "Wesley Blackburn", imageUrl: "https://avatars.githubusercontent.com/u/98054974?v=4" },
  { name: "Yonatan (Yoni) Lurie", imageUrl: "https://avatars.githubusercontent.com/u/92499732?v=4" },
  { name: "Yue Huang", imageUrl: "https://avatars.githubusercontent.com/u/93162290?v=4" },
  { name: "Zachary (Zach) Hoschar", imageUrl: "https://avatars.githubusercontent.com/u/56608122?v=4" },
  { name: "Zeus Ronzan", imageUrl: "https://avatars.githubusercontent.com/u/100141010?v=4" },
  { name: "Zhihong Liu", imageUrl: "https://avatars.githubusercontent.com/u/102339574?v=4" },

];

export default students;
