const students = [
  { name: "Alec Venida", imageUrl: "https://avatars.githubusercontent.com/u/97048214?v=4" },
  { name: "Alex Gonglach", imageUrl: "https://avatars.githubusercontent.com/u/54010874?v=4" },
  { name: "Antony (Tony or Anthony) Pizarro", imageUrl: "https://avatars.githubusercontent.com/u/61199533?v=4" },
  { name: "Attiya Kovenburg", imageUrl: "https://avatars.githubusercontent.com/u/89858837?v=4" },
  { name: "Benjamin (Ben) Waldee", imageUrl: "https://avatars.githubusercontent.com/u/104237728?v=4" },
  { name: "Cecilia Ou", imageUrl: "https://avatars.githubusercontent.com/u/103226832?v=4" },
  { name: "Chen Chen", imageUrl: "https://avatars.githubusercontent.com/u/47489094?v=4" },
  { name: "Connor Lam", imageUrl: "https://avatars.githubusercontent.com/u/104233383?v=4" },
  { name: "Da Wei (David) Ting", imageUrl: "https://avatars.githubusercontent.com/u/101853690?v=4" },
  { name: "Daniel Hoffmann", imageUrl: "https://avatars.githubusercontent.com/u/103540391?v=4" },
  { name: "Edgar Lee", imageUrl: "https://avatars.githubusercontent.com/u/101891232?v=4" },
  { name: "Edward Felipe Iii", imageUrl: "https://avatars.githubusercontent.com/u/75222415?v=4" },
  { name: "El Linzer", imageUrl: "https://avatars.githubusercontent.com/u/101808290?v=4" },
  { name: "Francisco Palacios", imageUrl: "https://avatars.githubusercontent.com/u/101391912?v=4" },
  { name: "Giordan Maniti", imageUrl: "https://avatars.githubusercontent.com/u/93215380?v=4" },
  { name: "Hazel Guzzetti", imageUrl: "https://avatars.githubusercontent.com/u/28935811?v=4" },
  { name: "Jason Chew", imageUrl: "https://avatars.githubusercontent.com/u/104326243?v=4" },
  { name: "Justin (JB) Kam", imageUrl: "https://avatars.githubusercontent.com/u/92565826?v=4" },
  { name: "Justine Jang", imageUrl: "https://avatars.githubusercontent.com/u/97000764?v=4" },
  { name: "Ray Charles (Ray) Henry", imageUrl: "https://avatars.githubusercontent.com/u/79509501?v=4" },
  { name: "Rudy Nguyen", imageUrl: "https://avatars.githubusercontent.com/u/14317966?v=4" },
  { name: "Tiffany Yang", imageUrl: "https://avatars.githubusercontent.com/u/32859211?v=4" },
  { name: "Tyler Jean", imageUrl: "https://avatars.githubusercontent.com/u/104518737?v=4" },
];

export default students;
